#!/system/bin/sh
MODDIR="${0%/*}"
PROFILE="$1"
case "$PROFILE" in balanced|performance|gaming|extreme) ;; *) exit 2 ;; esac
TMP="$MODDIR/config.sh.tmp"
{
  echo '# Auto-generated by Megatron WebUI'
  echo "PROFILE=\"$PROFILE\""
  echo 'THERMAL_SAFE=1'
  echo 'ADAPTIVE=1'
  echo 'LOG_ENABLED=1'
} > "$TMP" || exit 1
mv "$TMP" "$MODDIR/config.sh" || exit 1
chmod 0755 "$MODDIR/config.sh" 2>/dev/null
exec /system/bin/sh "$MODDIR/engine.sh"
